blog/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from blog import views, feeds


urlpatterns = patterns('',
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^categorie/(?P<categorie>\S+)$', login_required(views.CategorieView.as_view()), name='categorie'),
    url(r'^(?P<slug>\S+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<slug>\S+)/commenter$', login_required(views.CommentaireCreate.as_view()), name='commenter'),

    # TODO Le feed RSS ne fonctionne pas :(
    url(r'^feed/$', login_required(feeds.DerniersArticles()), name='feed'),
)

chete/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('website.urls', namespace="website")),

    url(r'^gps/', include('gps.urls', namespace="gps")),
    url(r'^sondages/', include('sondages.urls', namespace="sondages")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^photos/', include('photos.urls', namespace="photos")),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    url(r'^markdown/', include('django_markdown.urls')),
)

gps/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from gps.views import GPSView
from gps.views import UsersPosition

urlpatterns = patterns('',
    url(r'^users/$', login_required(UsersPosition.as_view()), name='users'),
    url(r'^$', login_required(GPSView.as_view()), name="index"),
)

website/urls.py
from django.conf.urls import patterns, url
from website.views import HomeView
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from website.admin import UserCreationForm
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^register/',
        CreateView.as_view(template_name='registration/register.html',
                           form_class=UserCreationForm,
                           success_url='/'),
        name='register'),
    url(r'^organisation/', staff_member_required(TemplateView.as_view(template_name='website/sheets.html'), ), name='organisation'),


    # Reset password
    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'registration/reset_confirm.html',
         'post_reset_redirect': '/done/'},
        name='reset_confirm'),
    url(r'^reset/$',
        'django.contrib.auth.views.password_reset',
        {'template_name': 'registration/reset.html',
         'email_template_name': 'registration/mails/reset_email.html',
         'subject_template_name': 'registration/mails/reset_subject.txt',
         'post_reset_redirect': '/reset/done/'},
        name='reset'),
    # TODO les templates définis dans registrations ne sont pas pris en compte, pk ?
    url(r'^done/$',
        'django.contrib.auth.views.password_reset_complete',
        name='reset_done'),
    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_done'),


    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),
)

website/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, user name and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
                                password=password,
                                username=username)
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='adresse email',
        max_length=255,
        unique=True,
        )
    username = models.CharField(max_length=20, verbose_name="nom d'utilisateur")
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False, verbose_name="membre de la chêteam")

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

website/views.py
from django.views import generic
from sondages.models import Question
from blog.models import Article
from django.utils import timezone


class HomeView(generic.ListView):
    model = Question
    template_name = "website/templates/website/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        if Question.objects.filter(open=True):
            context['last_question'] = Question.objects.filter(
                open=True,
                pub_date__lte=timezone.now(),
            ).latest('pub_date')
        context['last_article'] = Article.objects.filter(
            ouvert=True
        ).latest('date_de_parution')
        return context

website/templates/website/home.html
{% extends 'website/templates/website/layout.html' %}

{% load staticfiles %}

{% block style %}
    <link href="{% static 'website/css/home.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1>Bienvenue, {% if user.is_authenticated %}{{ user.username }}{% else %}ami chêteur !{% endif %}</h1>
            <p>Toutes les dernières actus de la Chête ici.</p>
            <p>Et comme on est pas des batards, on te présente même le site !</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button" id="click_me" onclick="yes();">Oh oui, clique moi fort ! &raquo;</a></p>
            <script>
                clicks = 0;
                function yes() {
                    alert('Plus fort !');
                    clicks++;
                    if(clicks==2){
                        alert('Ce que tu cliques bien et fort !');
                        alert('OH !');
                        alert('OUI !');
                        clicks=0;
                    }
                }
            </script>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h2>Dernier sondage :</h2>
            {% if last_question %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>{{ last_question.question_text }}<br/><small>Question posée le {{ last_question.pub_date }}</small></p>
                        <a class="btn btn-sm btn-primary" href="{% url 'sondages:detail' last_question.slug %}" role="button">Voir les choix et voter</a>
                    </div>
                </div>
            {% else %}
                <p>Bientôt un nouveau sondage ! Mais tu peux regarder les sondages terminés en dessous.</p>
            {% endif %}
        </div>

        <div class="col-md-6">
            <h2>Dernier article :</h2>
            {% if last_article %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>{{ last_article.titre }}<br/><small>Article publié le {{ last_article.date_de_parution }}</small></p>
                        <a class="btn btn-sm btn-primary" href="{% url 'blog:detail' last_article.slug %}" role="button">Lire</a>
                    </div>
                </div>
            {% else %}
                <p>Bientôt un nouvel article !</p>
            {% endif %}
        </div>

        {% comment %}<div class="col-md-4">
            <h2>Derniere photo :</h2>
            {% if False %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>{{ last_question.question_text }}<br/><small>Question posée le {{ last_question.pub_date }}</small></p>
                        <a class="btn btn-sm btn-primary" href="{% url 'sondages:detail' last_question.id %}" role="button">Voir les choix et voter</a>
                    </div>
                </div>
            {% else %}
                <p>Pas de photos disponibles pour le moment :(</p>
            {% endif %}
        </div>{% endcomment %}
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">Les sondages. <span class="text-muted">Ton avis ne compte pas.</span></h2>
            <p class="lead">Parce que chaques années, la Chête se doit d'entérer les éditions précédentes, on a besoin de ton avis !</p>
            <p><a class="btn btn-primary btn-lg" href="{% url "sondages:index" %}" role="button">Voir les sondages &raquo;</a></p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" src="{% static "website/images/we_need_you.jpg" %}" alt="We need you for the Chête !">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
            <h2 class="featurette-heading">Viendre ! <span class="text-muted">A deux c'est mieux.</span></h2>
            <p class="lead">Parce qu'on t'aime, on t'as même fait un GPS, c'est pas beau ça ?</p>
            <p><a class="btn btn-primary btn-lg" href="{% url "gps:index" %}" role="button">Viendre à La Chête &raquo;</a></p>
        </div>
        <div class="col-md-5 col-md-pull-7">
            <img class="featurette-image img-responsive center-block" src="{% static "website/images/satellite.jpg" %}" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">

    {% comment %}<div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">Les photos. <span class="text-muted">Les souvenirs.</span></h2>
            <p class="lead">Publie directement les photos sur le site de la Chête !</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Voir les photos &raquo;</a></p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" src="{% static "website/images/photo.jpg" %}" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">{% endcomment %}

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">Blog. <span class="text-muted">La force des années 2000.</span></h2>
            <p class="lead">Parce qu'on est old school, on maintiens un blog avec les actualité de la Chête. Pleins d'infos inutiles à lire.</p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'blog:index' %}" role="button">Voir les articles &raquo;</a></p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" src="{% static "website/images/blog.gif" %}" alt="Generic placeholder image">
        </div>
    </div>

{% endblock %}

website/templates/website/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/images/favicon.ico">

    <title>{% block title %}La Chête - Un champ, une fête !{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <link href="/static/css/global.css" rel="stylesheet">

    <!-- Custom styles used by templates -->
    {% block style %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    {% if user.is_authenticated %}
        <script src="{% static "gps/update_position.js" %}"></script>
    {% endif %}
    <!-- Custom scripts -->
    {% block script %}{% endblock %}
</head>
<body>

{% block nav %}
    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url "website:home" %}">La Chête</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            {# C'est pas tip top pour determiner le menu actif, mais je voulais un truc simple :) #}
                            <li  class="{% ifequal request.path|slice:":5" '/'%}active{% endifequal%}" ><a href="{% url "website:home" %}">Accueil</a></li>
                            <li class="{% ifequal request.path|slice:":5" '/sond'%}active{% endifequal%}" ><a href="{% url 'sondages:index' %}">Sondages</a></li>
                            <li class="{% ifequal request.path|slice:":5" '/gps/'%}active{% endifequal%}" ><a href="{% url 'gps:index' %}">Viendre !</a></li>
                            {# <li class="{% ifequal request.path|slice:":5" '/phot'%}active{% endifequal%}" ><a href="#">Photos</a></li> #}
                            <li class="{% ifequal request.path|slice:":5" '/blog'%}active{% endifequal%}" ><a href="{% url 'blog:index' %}">Blog</a></li>
                            {% if user.is_staff %}
                                <li class="{% ifequal request.path '/organisation/'%}active{% endifequal%}" ><a href="{% url 'website:organisation' %}">Organisation</a></li>
                            {% endif %}
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li><a href="/accounts/logout" role="button">Se déconnecter</a></li>
                            {% else %}
                                <li><a href="{% url 'website:register' %}" role="button">S'enregistrer</a></li>
                                <li><a href="/accounts/login" role="button">Se connecter</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </div>
{% endblock %}


<div class="container">
    {% block content %}{% endblock %}
</div>


<div id="footer">
    <hr>
    <div class="container">
        <p class="pull-right"><a href="#">Haut de page</a></p>
        <p><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> La Chête ! Site réalisé avec amour par <a href="https://github.com/Al-Ouest">Al Ouest</a> & <a href="https://github.com/Ganapati">Ganapati</a> <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></p>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/jquery-1.11.2.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
{%  comment %}
TODO IE10 viewport hack for Surface/desktop Windows 8 bug -> WTF is this ?
{% endcomment %}
<!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
</body>
</html>

website/templates/website/sheets.html
{% extends 'website/layout.html' %}

{% block title%}La Chête - Organisation{% endblock %}

{% block content %}
    <h1>Organisation</h1>
    <p>Cliquer pour modifier le tableau : <a href="https://docs.google.com/spreadsheets/d/1JY5y38M0aTr-jU1oTHyeLpMiN4hj1-5InX1Kah7lwOY/edit?usp=sharing" class="btn btn-primary" target="_blank">Editer</a></p>
    <iframe width="100%" height="400" src="https://docs.google.com/spreadsheets/d/1JY5y38M0aTr-jU1oTHyeLpMiN4hj1-5InX1Kah7lwOY/pubhtml?widget=true&amp;headers=false"></iframe>
{% endblock %}