blog/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from blog import views, feeds


urlpatterns = patterns('',
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^categorie/(?P<categorie>\S+)$', login_required(views.CategorieView.as_view()), name='categorie'),
    url(r'^(?P<slug>\S+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<slug>\S+)/commenter$', login_required(views.CommentaireCreate.as_view()), name='commenter'),

    # TODO Le feed RSS ne fonctionne pas :(
    url(r'^feed/$', login_required(feeds.DerniersArticles()), name='feed'),
)

chete/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('website.urls', namespace="website")),

    url(r'^gps/', include('gps.urls', namespace="gps")),
    url(r'^sondages/', include('sondages.urls', namespace="sondages")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^photos/', include('photos.urls', namespace="photos")),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    url(r'^markdown/', include('django_markdown.urls')),
)

gps/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from gps.views import GPSView
from gps.views import UsersPosition

urlpatterns = patterns('',
    url(r'^users/$', login_required(UsersPosition.as_view()), name='users'),
    url(r'^$', login_required(GPSView.as_view()), name="index"),
)

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.conf import settings
import itertools


class Categorie(models.Model):
    nom = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.nom


class ArticleQuerySet(models.QuerySet):
    def published(self):
        return self.filter(ouvert=True)


class Article(models.Model):
    titre = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, editable=False)
    categorie = models.ManyToManyField(Categorie)
    ouvert = models.BooleanField(default=True)
    date_de_parution = models.DateTimeField(auto_now_add=True, editable=False)
    date_de_modification = models.DateTimeField(auto_now=True)
    contenu = models.TextField()
    video = models.URLField(blank=True, help_text="Copie/colle l'url d'une vidéo YouTube ici et elle sera "
                                                  "insérée à la fin de l'article.")

    objects = ArticleQuerySet.as_manager()

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"
        ordering = ["-date_de_parution"]

    def save(self, *args, **kwargs):
        self.slug = orig = slugify(self.titre)
        for x in itertools.count(1):
            if not Article.objects.filter(slug=self.slug).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        self.video = self.video.replace('watch?v=', 'embed/')
        super(Article, self).save(*args, **kwargs)


class Commentaire(models.Model):
    titre = models.CharField(max_length=25)
    contenu = models.TextField()
    article = models.ForeignKey(Article)
    utilisateur = models.ForeignKey(settings.AUTH_USER_MODEL)
    date_de_parution = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django.forms import ModelForm
from blog.models import Commentaire


class CommentaireForm(ModelForm):
    class Meta:
        model = Commentaire
        fields = ['titre', 'contenu']

blog/views.py
from blog.models import Article, Categorie, Commentaire
from django.views import generic
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse


class IndexView(generic.ListView):
    queryset = Article.objects.published()
    model = Article
    template_name = 'blog/index.html'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['categories'] = Categorie.objects.distinct()
        context['index'] = True
        return context


class CategorieView(IndexView):
    def get_queryset(self):
        categorie = get_object_or_404(Categorie, nom=self.kwargs['categorie'])
        return Article.objects.filter(categorie=categorie)

    # TOFIX Bon, là c'est pas supersuper, je répete ce que j'ai fait pour l'indexview ...
    # J'aurais aimé garder le context de mon index view et juste filer 'categorie' en plus.
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['categories'] = Categorie.objects.distinct()
        context['index'] = False
        context['categorie'] = self.kwargs['categorie']
        return context


class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/article.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['categories'] = Categorie.objects.distinct()
        return context


class CommentaireCreate(generic.CreateView):
    model = Commentaire
    fields = ['titre', 'contenu']

    def get_success_url(self):
        return reverse("blog:detail", kwargs={"slug": self.kwargs['slug']})

    def form_valid(self, form):
        commentaire = form.save(commit=False)
        commentaire.article = get_object_or_404(Article, slug=self.kwargs['slug'])
        commentaire.utilisateur = self.request.user
        commentaire.save()
        return HttpResponseRedirect(self.get_success_url())

blog/templates/blog/article.html
{% extends "blog/templates/blog/layout.html" %}

{% load django_markdown %}

{% block post %}
    <div class="col-sm-8 blog-main">

        <div class="blog-post">

            <h2 class="blog-post-title"><a href="{% url 'blog:detail' slug=article.slug %}">{{ article.titre }}</a></h2>
            <p class="blog-post-meta">
                {% for cat in article.categorie.all %}
                    <a href="{% url 'blog:categorie' cat %}" ><span class="label label-info"><strong>{{ cat }}</strong></span></a>
                {% endfor %}
                Publié le {{ article.date_de_parution }}
            </p>

            <p>{{ article.contenu|markdown }}</p>

            {% if article.video %}
                <iframe width="640" height="390" src="{{ article.video }}" frameborder="0" style="margin: 20px 0 20px 0" allowfullscreen></iframe>
            {% endif %}

            <h3 id="commentaires">Vos commentaires alakon</h3>

            {% if article.commentaire_set.all.exists %}
                {% for com in article.commentaire_set.all %}
                    <div class="well">
                        <h3>{{ com.titre }}{% if com.utilisateur.is_staff %}<small class="text-danger"> Réponse Chêteam</small>{% endif %}</h3>
                        <p class="small text-muted">Commentaire posté par <b class="text-info">{{ com.utilisateur.username }}</b> le {{ com.date_de_parution }}</p>
                        <p>{{ com.contenu }}</p>
                    </div>
                {% endfor %}
            {% else %}
                <p>Aucuns commentaires pour le moment.</p>
            {% endif %}
            {# TODO Gérer les erreurs ! Affichage du template commentaire_form dans un modal par exemple #}
            <form method="post" action="{% url 'blog:commenter' article.slug %}" class="form-horizontal">
                {% if form.subject.errors %}
                    <ol>
                        {% for error in form.subject.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                        {% endfor %}
                    </ol>
                {% endif %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h2 class="panel-title">Commenter</h2>
                    </div>
                    <div class="panel-body">
                        <fieldset>
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="titre" class="col-lg-2 control-label">Titre</label>
                                <div class="col-lg-10">
                                    <input id="titre" type="text" name="titre" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="contenu" class="col-lg-2 control-label">Message</label>
                                <div class="col-lg-10">
                                    <textarea id="contenu" name="contenu" class="form-control" rows="3" required></textarea>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-default form-control">Poster</button>
                        </fieldset>
                    </div>
                </div>
            </form>

        </div>
    </div>

{% endblock %}

blog/templates/blog/commentaire_form.html
<div class="col-sm-8 blog-main">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>
</div>

blog/templates/blog/index.html
{% extends "blog/layout.html" %}

{% load django_markdown %}

{% block subtitle %}
    {% if not index %}
        <h3 class="text-info">Articles avec la catégorie : {{ categorie }}</h3>
    {% endif %}
{% endblock %}

{% block post %}
    <div class="col-sm-8 blog-main">

        {% if object_list.count == 0 %}
            <p>Pas encore d'articles pour le moment, mais ça va venir !</p>
        {% endif %}

        {% for article in object_list %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{% url 'blog:detail' slug=article.slug %}">{{ article.titre }}</a></h2>

                <p class="blog-post-meta">
                    {% for cat in article.categorie.all %}
                        <a href="{% url 'blog:categorie' cat %}" ><span class="label label-info"><strong>{{ cat }}</strong></span></a>
                    {% endfor %}
                    Publié le {{ article.date_de_parution }}
                </p>
                <p>{{ article.contenu|markdown }}</p>

                {% if article.video %}
                    <iframe width="640" height="390" src="{{ article.video }}" frameborder="0" style="margin: 20px 0 20px 0" allowfullscreen></iframe>
                {% endif %}
            
                <ul class="nav nav-pills">
                    <li><a href="{% url "blog:detail" article.slug %}">Commentaires <span class="badge">{{ article.commentaire_set.all.count }}</span></a></li>
                </ul>
            </div><!-- /.blog-post -->
        {% endfor %}

        <nav>
            <ul class="pager">
                {% if page_obj.has_previous %}
                    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">← Précédents</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="next"><a href="?page={{ page_obj.next_page_number }}">Suivants →</a></li>
                {% endif %}
            </ul>
        </nav>
    </div><!-- /.blog-main -->
{% endblock %}

blog/templates/blog/layout.html
{% extends "website/templates/website/layout.html" %}

{% load static %}

{% block title %}La Chête - blog{% endblock %}

{% block style %}
    <link href="{% static 'blog/blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="blog-container">

        <div class="blog-header">
            <h1 class="blog-title">Le blog</h1>
            <p class="lead blog-description">Toutes les niouzes sur la plus belle teuf dans un champ et bien plus encore.</p>
            {% block subtitle %}{% endblock %}
        </div>

        <div class="row">

            {% block post %}
            {% endblock %}

            <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
                <div class="sidebar-module sidebar-module-inset">
                    <h4>A propos</h4>
                    <p>Nous <em> - la chêteam - </em> voulons le meilleur pour nos chêteur. En vous proposant les
                        dernières nouvelles de l'événement sur ce blog et en relayant tout ça sur Facebook, on fait en
                        sorte que tu ne rates rien !</p>
                </div>
                <div class="sidebar-module">
                    <h4>Catégories</h4>
                    <ol class="list-unstyled">
                        {% for categorie in categories %}
                            <li><a href="{% url 'blog:categorie' categorie %}">{{ categorie }}</a></li>
                        {% endfor %}
                    </ol>
                </div>
                <div class="sidebar-module">
                    <h4>Y'a aussi ...</h4>
                    <ol class="list-unstyled">
                        <li><a href="https://www.facebook.com/events/1435450763417700/" target="_blank">Facebook</a></li>
                    </ol>
                </div>
            </div><!-- /.blog-sidebar -->

        </div><!-- /.row -->
    </div>

{% endblock %}