chete/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('website.urls', namespace="website")),

    url(r'^gps/', include('gps.urls', namespace="gps")),
    url(r'^sondages/', include('sondages.urls', namespace="sondages")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^photos/', include('photos.urls', namespace="photos")),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    url(r'^markdown/', include('django_markdown.urls')),
)

gps/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from gps.views import GPSView
from gps.views import UsersPosition

urlpatterns = patterns('',
    url(r'^users/$', login_required(UsersPosition.as_view()), name='users'),
    url(r'^$', login_required(GPSView.as_view()), name="index"),
)

sondages/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from sondages.views import IndexView, DetailView, ResultsView, vote


urlpatterns = patterns('',
    url(r'^$', login_required(IndexView.as_view()), name='index'),
    url(r'^(?P<slug>\S+)/$', login_required(DetailView.as_view()), name='detail'),
    url(r'^(?P<slug>\S+)/resultats$', login_required(ResultsView.as_view()), name='resultats'),
    url(r'^(?P<slug>\S+)/vote$', login_required(vote), name='vote'),
)

sondages/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.text import slugify
import itertools


class Question(models.Model):
    question_text = models.CharField('question', max_length=200)
    slug = models.SlugField(max_length=200, unique=True, editable=False)
    pub_date = models.DateField('date de publication', help_text="Si la date est dans le futur, "
                                                                 "la question sera publiée à cette date.")
    open = models.BooleanField('question ouverte au vote ?', default=True, help_text='Décocher cette case pour fermer '
                                                                                     'la question')
    votants = models.ManyToManyField(settings.AUTH_USER_MODEL, editable=False)

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"
        ordering = ["-pub_date"]

    def save(self, *args, **kwargs):
        self.slug = orig = slugify(self.question_text)
        for x in itertools.count(1):
            if not Question.objects.filter(slug=self.slug).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        super(Question, self).save(*args, **kwargs)


class Choix(models.Model):
    question = models.ForeignKey(Question)
    choix_text = models.CharField('choix', max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "choix"

    def __str__(self):
        return self.choix_text

sondages/forms.py
from django import forms


class VoteForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

sondages/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from sondages.models import Question, Choix


class IndexView(generic.ListView):
    model = Question
    template_name = 'sondages/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if Question.objects.all().exists():
            test = Question.objects.filter(
                pub_date__lte=timezone.now(),
                open=True
            ).order_by('-pub_date')
            if test:
                context['last_question'] = test[0]
                """ latest_question_list ne contient pas la dernière question posée """
                context['latest_question_list'] = test[1:]

            context['closed_question_list'] = Question.objects.filter(
                pub_date__lte=timezone.now(),
                open=False
            ).order_by('-pub_date')

        return context


class DetailView(generic.DetailView):
    model = Question
    template_name = 'sondages/detail.html'

    def get_queryset(self):
        """
        Exclu les questions qui ne sont pas encore publiées.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        if self.request.user in self.object.votants.all():
            context['vote'] = True
        else:
            context['vote'] = False
        return context


class ResultsView(DetailView):
    template_name = 'sondages/resultats.html'


def vote(request, slug):
    p = get_object_or_404(Question, slug=slug)
    # Si la question est close, ou si l'utilisateur a déjà voté
    # on redirige vers le résultat du sondage = sécurité suplémentaire
    if (not p.open) or (request.user in p.votants.all()):
        return HttpResponseRedirect(reverse('sondages:resultats', args=(p.slug,)))
    try:
        selected_choix = p.choix_set.get(pk=request.POST['choix'])
    except (KeyError, Choix.DoesNotExist):
        # Réaffiche le formulaire de vote de la question
        return render(request, 'sondages/detail.html', {
            'question': p.slug,
            'error_message': "Vous n'avez pas séléctionné votre choix.",
            })
    else:
        selected_choix.votes += 1
        selected_choix.save()
        p.votants.add(request.user)
        p.save()
        return HttpResponseRedirect(reverse('sondages:resultats', args=(p.slug,)))

sondages/templates/sondages/detail.html
{% extends "website/templates/website/layout.html" %}

{% block title %}La Chête - sondages{% endblock %}

{% block content %}

    <h1>{{ question.question_text }} <small>Sélectionne ton choix et vote !</small></h1>

    {% if error_message %}
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ error_message }}
        </div>
    {% endif %}

    {% if vote %}
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            Tu as déjà voté !
        </div>
    {% endif %}

    {% if question.open and not vote %}
        <form action="{% url 'sondages:vote' question.slug %}" method="post">
            {% csrf_token %}
            {% for choix in question.choix_set.all %}
                <input type="radio" name="choix" id="choix{{  forloop.counter }}" value="{{ choix.id }}" />
                <label for="choix{{  forloop.counter }}">{{ choix.choix_text }}</label><br />
            {% endfor %}
            <button type="submit" class="btn btn-primary">Voter</button>
            <a href="{% url 'sondages:index' %}" class="btn btn-info"><span class="glyphicon glyphicon-arrow-left"> Revenir aux sondages</span></a>
        </form>
    {% else %}
        <a href="{% url 'sondages:resultats' question.slug %}" class="btn btn-info"><span class="glyphicon glyphicon-arrow-right"> Voir les résultats</span></a>
    {% endif %}

{% endblock %}

sondages/templates/sondages/index.html
{% extends "website/templates/website/layout.html" %}

{% block title %}La Chête - Les sondages{% endblock %}

{% block content %}

    <div class="jumbotron">
        <h1>Les sondages</h1>
        {% if last_question %}
            <p class="lead">Dernière question posée :</p>
            <div class="panel panel-default">
                <div class="panel-body" {% if user in last_question.votants.all %}style="background-color: #DFF0D8;"{% endif %}>
                    <p>{{ last_question.question_text }} <small class="text-muted">Question posée le {{ last_question.pub_date }}</small></p>
                    <a class="btn btn-primary" href="{% url 'sondages:detail' last_question.slug %}" role="button">Voir les choix et voter</a>
                </div>
            </div>
        {% else %}
            <p>Bientôt un nouveau sondage ! Mais tu peux regarder les sondages terminés en dessous.</p>
        {% endif %}
    </div>

    <p class="text-info">Les questions pour lesquelles tu as déjà voté apparaissent en vert.</p>

    <h2>Autres sondages en cours</h2>
    {% if latest_question_list %}
        <table class="table table-hover">
            {% for question in latest_question_list %}
                <tr {% if user in question.votants.all %}class="success"{% endif %}>
                    <td><a href="{% url 'sondages:detail' question.slug %}">{{ question.question_text }}</a></td>
                    <td>Question posée le {{ question.pub_date }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Aucuns sondages disponibles pour le moment.</p>
    {% endif %}

    {# TODO Le tableau des sondages terminé ne s'affiche pas comme celui des autres sondages en cours, pourkeua ?#}
    <h2>Sondages terminés</h2>
    {% if closed_question_list %}
        <table class="table table-hover">
            {% for question in closed_question_list %}
                <tr {% if user in question.votants.all %}class="success"{% endif %}>
                    <td><a href="{% url 'sondages:resultats' question.slug %}">{{ question.question_text }}</a></td>
                    <td>Question posée le {{ question.pub_date }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Aucuns sondages terminés.</p>
    {% endif %}

{% endblock %}

sondages/templates/sondages/resultats.html
{% extends "website/templates/website/layout.html" %}

{% block title %}La Chête - Les sondages{% endblock %}

{% block content %}

    <h1>{{ question.question_text }} <small>Les résultats</small></h1>

    {% if not question.open %}
        <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            Ce sondage est actuellement <strong>terminé</strong>, les votes sont clos.
        </div>
    {% else %}
        {% if request.user.username in question.votants.all %}
            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>Vous avez déjà voté !</strong>
            </div>
        {% endif %}
    {% endif %}

    <ul>
        {% for choix in question.choix_set.all %}
            <li>{{ choix.choix_text }} -- {{ choix.votes }} vote{{  choix.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <p>Question ouverte le {{ question.pub_date }}</p>
    <a href="{% url 'sondages:index' %}" class="btn btn-info"><span class="glyphicon glyphicon-arrow-left"> Revenir aux sondages</span></a>

{% endblock %}